### ISSUE TITLE
witruimte

### ISSUE THREAD

**Issue by r20222** [Ronabundy1/fix-the-flow-interactive-website#4]
De website ziet er mooi uit! 👍 

https://github.com/Ronabundy1/fix-the-flow-interactive-website/blob/e0705245c30d87122a744df71e9c7073d6da89df/index.html#L99-L121

Misschien is het handig om deze witruimte weg te halen?

**Comment by Ronabundy1** [comment]
dankjewel wit ruimte heb ik weggehaald
